---
# Copyright 2018 widdix GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
AWSTemplateFormatVersion: '2010-09-09'
Description: 'cfn-modules: Serverless image resize example'
Resources:
  Alerting:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        Email: 'email@domain.com' # replace with your email address to receive alerts
        # HttpsEndpoint: 'https://api.marbot.io/v1/endpoint/xyz' # or uncommnet and receive alerts in Slack using marbot.io
      TemplateURL: './node_modules/@cfn-modules/alerting/module.yml'
  BucketRaw:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        Versioning: 'false'
        LambdaEventTargetLambdaModule1: !GetAtt 'FunctionResize.Outputs.StackName'
      TemplateURL: './node_modules/@cfn-modules/s3-bucket/module.yml'
  BucketResized:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        Versioning: 'false'
      TemplateURL: './node_modules/@cfn-modules/s3-bucket/module.yml'
  FunctionResize:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        AlertingModule: !GetAtt 'Alerting.Outputs.StackName'
        Handler: 'resize.handler'
        Runtime: 'nodejs12.x'
        DependencyModule1: !GetAtt 'BucketResized.Outputs.StackName'
      TemplateURL: './node_modules/@cfn-modules/lambda-function/module.yml'
Outputs:
  BucketNameRaw:
    Value: !GetAtt 'BucketRaw.Outputs.Name'
  BucketNameResized:
    Value: !GetAtt 'BucketResized.Outputs.Name'
