---
# Copyright 2018 widdix GmbH
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
AWSTemplateFormatVersion: '2010-09-09'
Description: 'cfn-modules: Serverless IAM example'
Resources:
  Alerting:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        Email: 'email@domain.com' # replace with your email address to receive alerts
        # HttpsEndpoint: 'https://api.marbot.io/v1/endpoint/xyz' # or uncommnet and receive alerts in Slack using marbot.io
      TemplateURL: './node_modules/@cfn-modules/alerting/module.yml'
  Queue:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        AlertingModule: !GetAtt 'Alerting.Outputs.StackName'
        DelaySeconds: '60'
      TemplateURL: './node_modules/@cfn-modules/sqs-queue/module.yml'
  Table:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        AlertingModule: !GetAtt 'Alerting.Outputs.StackName'
      TemplateURL: './node_modules/@cfn-modules/dynamodb-table/module.yml'
  Bucket:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        Versioning: 'false'
      TemplateURL: './node_modules/@cfn-modules/s3-bucket/module.yml'
  Function:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      Parameters:
        AlertingModule: !GetAtt 'Alerting.Outputs.StackName'
        Handler: 'example.handler'
        Runtime: 'nodejs12.x'
        DependencyModule1: !GetAtt 'Queue.Outputs.StackName'
        DependencyModule2: !GetAtt 'Table.Outputs.StackName'
        DependencyModule3: !GetAtt 'Bucket.Outputs.StackName'
      TemplateURL: './node_modules/@cfn-modules/lambda-function/module.yml'
Outputs:
  RoleName:
    Value: !GetAtt 'Function.Outputs.RoleName'
