name: Lint
on:
  push:
    branches: [master]
  pull_request:
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v2'
    - uses: 'actions/setup-python@v2'
      with:
        python-version: '3.8'
    - name: yamlllint
      run: |
        pip install yamllint==1.26.3
        find examples -type f -name example.yml | while read file; do set -ex && yamllint "$file"; done;
    - name: cfn-lint
      run: |
        pip install cfn-lint==0.59.1
        find examples -type f -name example.yml | while read file; do set -ex && cfn-lint -t "$file"; done;
    - name: license
      run: |
        find examples -type f -name example.yml -not -name .eslintrc.yml | while read file; do set -ex && grep -q "LICENSE-2.0" "$file"; done;